spring.application.name=quiz_service

server.port=8082

spring.datasource.url=jdbc:postgresql://ep-dawn-fire-a5c4pzw9-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_SwpGfRt1iQ2a
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.instance.client.serverUrl.defaultZone=http://localhost:8761/